init:
- git config --global core.autocrlf true
install:
- ps: Install-Product node 8 x64
branches:
  only:
  - dev
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
build_script:
- ps: .\build.cmd
clone_depth: 1
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
test: 'off'
deploy: 'off'
os: Visual Studio 2017
before_test:
  - choco install googlechrome --ignore-checksum
  - npm install -g selenium-standalone@latest
  - selenium-standalone install
  - ps: $SeleniumProcess = Start-Process "selenium-standalone" -ArgumentList "start" -PassThru
after_test:
  - ps: Stop-Process -Id $SeleniumProcess.Id
