trigger:
- master
- release/*

# See https://github.com/aspnet/BuildTools
resources:
  repositories:
  - repository: buildtools
    type: github
    endpoint: DotNet-Bot GitHub Connection
    name: aspnet/BuildTools
    ref: refs/heads/release/2.2

phases:
- template: .vsts-pipelines/templates/phases/default-build.yml@buildtools
  parameters:
    agentOs: Windows
    beforeBuild:
    - task: NodeTool@0
      displayName: Use Node 8.x
      inputs:
        versionSpec: 8.x
    - script: npm install -g selenium-standalone
      displayName: Install selenium
    - script: selenium-standalone install
      displayName: Install selenium drivers
    - powershell: $SeleniumProcess = Start-Process "selenium-standalone"  -ArgumentList "start" -PassThru
      displayName: Start selenium standalone
    afterBuild:
    - powershell: Stop-Process -Id $SeleniumProcess.Id
      displayName: Stop selenium standalone

- phase:
  queue: Hosted macOS Preview
  variables:
    DOTNET_HOME: $(Agent.WorkFolder)/.dotnet
  steps:
  - task: NodeTool@0
    displayName: Use Node 8.x
    inputs:
      versionSpec: 8.x
  - script: ./run.sh install-tools; $(Agent.WorkFolder)/.dotnet/dotnet dev-certs https
    displayName: install certs
  - script: npm install -g selenium-standalone
    displayName: Install selenium
  - script: selenium-standalone install
    displayName: Install selenium drivers
  - script: selenium-standalone start & ; .\build.cmd -ci ; selenium-standalone stop
    displayName: Start selenium standalone and run build

- phase:
  queue: Hosted Linux Preview
  variables:
    DOTNET_HOME: $(Agent.WorkFolder)/.dotnet
  steps:
  - task: NodeTool@0
    displayName: Use Node 8.x
    inputs:
      versionSpec: 8.x
  - script: ./run.sh install-tools; $(Agent.WorkFolder)/.dotnet/dotnet dev-certs https
    displayName: install certs
  - script: npm install -g selenium-standalone
    displayName: Install selenium
  - script: selenium-standalone install
    displayName: Install selenium drivers
  - script: selenium-standalone start & ; .\build.cmd -ci ; selenium-standalone stop
    displayName: Start selenium standalone and run build
